language: node_js
node_js:
  - node
  - lts/*
services:
  - couchdb
notifications:
  email:
    - dom@w3.org
before_script:
  - cp ./test/config-test.json ./config.json
  - node store.js "./test/config-test.json"
script:
  npm test
